#syntax=docker/dockerfile:1

FROM composer:latest

WORKDIR /src/app/

ENV APP_ENV=development
ENV APP_DEBUG=true

COPY ./composer.json /src/app/
COPY ./vite.config.js /src/app/
COPY ./package.json /src/app/
COPY ./artisan /src/app/artisan
COPY ./storage/ /src/app/storage/
COPY ./routes/ /src/app/routes/
COPY ./public/ /src/app/public/
COPY ./database/ /src/app/database/
COPY ./config/ /src/app/config/
COPY ./bootstrap/ /src/app/bootstrap/
COPY ./app/ /src/app/app/
COPY ./.env.example /src/app/

RUN composer install
RUN composer setup

CMD composer start

EXPOSE 8000
