#syntax=docker/dockerfile:1

FROM python:latest

WORKDIR /src/app/

COPY ./src/ /src/app/src/
COPY ./static/ /src/app/static/
COPY ./test/ /src/app/test/
COPY ./requirements.txt /src/app/

RUN pip install -r ./requirements.txt

CMD python -m unittest discover -s test -p "test*.py" -v
