#syntax=docker/dockerfile:1

FROM elixir:latest

WORKDIR /src/app/

COPY ./mix.exs /src/app/
COPY ./.formatter.exs /src/app/
COPY ./priv/ /src/app/priv/
COPY ./lib/ /src/app/lib/
COPY ./config/ /src/app/config/

RUN mix deps.get

CMD mix phx.server

EXPOSE 4000